version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: medifind_db
    environment:
      POSTGRES_DB: medifind_db
      POSTGRES_USER: usuario_db
      POSTGRES_PASSWORD: password_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # --- ESTA ES LA LÍNEA NUEVA ---
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: .
    container_name: medifind_backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/medifind_db
      SPRING_DATASOURCE_USERNAME: usuario_db
      SPRING_DATASOURCE_PASSWORD: password_db

volumes:
  postgres_data: