spring.application.name=MediFind_SpringV

# Server Configuration
server.port=8080

# Database Configuration (PostgreSQL via Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/medifind_db
spring.datasource.username=baxava
spring.datasource.password=medifind_baxava
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf Configuration (just in case)
spring.thymeleaf.cache=false
